name: pine_admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.20.2
  lottie: ^3.3.1
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  diacritic: ^0.1.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_dropzone: ^4.2.1
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1
  multi_select_flutter: ^4.1.3
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.1
  flutter_local_notifications: ^19.0.0

  #Web Specific
  web: ^1.1.0
  http: ^1.3.0
  html: ^0.15.5
  fl_chart: ^0.68.0
  data_table_2: ^2.5.18
  url_strategy: ^0.3.0
  universal_html: ^2.2.4

  #State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  #Firebase
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.3

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #----------- Local Assets ----------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/images/products/
    - assets/icons/payment_methods/
    - assets/icons/brands/
    - assets/icons/categories/

  #----------- Local Fonts -----------#

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cabin-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cabin-Italic.ttf
          style: italic
        - asset: assets/fonts/Cabin-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cabin-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Cabin-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 800
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
