name: pine
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

#--------------- PACKAGES ---------------
dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  logger: ^2.0.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  flutter_slidable: ^4.0.0
  timeline_tile: ^2.0.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.2
  firebase_storage: ^12.4.4
  cached_network_image: ^3.4.1

  # payment

#--------------- PACKAGES END ---------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/pine-logo-white.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logos/pine-logo-white.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ---------------
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_method/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/

  #--------------- LOCAL FONTS ---------------
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cabin-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cabin-Italic.ttf
          style: italic
        - asset: assets/fonts/Cabin-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cabin-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Cabin-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 800

    - family: Agbalumo
      fonts:
        - asset: assets/fonts/Agbalumo-Regular.ttf
          weight: 400
